# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('django_social_app', '0001_initial'), ('django_social_app', '0002_auto_20151220_1310'), ('django_social_app', '0003_auto_20151221_0401'), ('django_social_app', '0004_auto_20151221_0402')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='energy_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField()),
                ('save_time', models.DateTimeField(verbose_name='energy save time')),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('energy_today', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='maintain_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_type', models.IntegerField()),
                ('maintain_time', models.DateTimeField(verbose_name='maintain save time')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_social_app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('manager', models.BooleanField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='maintain_history',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_social_app.staff'),
        ),
        migrations.AddField(
            model_name='energy_history',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_social_app.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='energy_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintain_1000h',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintain_200h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 2, 40, 36181, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintain_600h',
            field=models.DateTimeField(default=None),
        ),
    ]
