# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='energy_today',
            field=models.IntegerField(default=0),
        ),
    ]
