# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0002_auto_20151220_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintain_schedule',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='maintain_1000h',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintain_200h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 1, 13, 477265, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintain_600h',
            field=models.DateTimeField(default=None),
        ),
        migrations.DeleteModel(
            name='maintain_schedule',
        ),
    ]
