# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0003_auto_20151221_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintain_200h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 2, 40, 36181, tzinfo=utc)),
        ),
    ]
