# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0004_auto_20151221_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintain_200h',
            field=models.DateTimeField(default=None),
        ),
    ]
