# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0005_auto_20151221_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintain_1000h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 11, 13, 457306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintain_200h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 11, 13, 457547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintain_600h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 11, 13, 457518, tzinfo=utc)),
        ),
    ]
