# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0006_auto_20151221_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintain_1000h',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintain_200h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 13, 14, 386213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintain_600h',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 21, 4, 13, 14, 385945, tzinfo=utc)),
        ),
    ]
