# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0008_auto_20151221_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='maintain_1000h',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='maintain_200h',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='maintain_600h',
        ),
    ]
