# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0009_auto_20151221_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintain_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_time', models.DateTimeField(verbose_name='maintain time')),
                ('maintain_type', models.IntegerField(verbose_name='maintain type')),
                ('maintain_time_remain', models.IntegerField(default=1000)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_social_app.machine')),
            ],
        ),
    ]
