# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0010_maintain_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy_history',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='maintain_history',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='maintain_history',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='maintain_schedule',
            name='machine',
        ),
        migrations.DeleteModel(
            name='energy_history',
        ),
        migrations.DeleteModel(
            name='machine',
        ),
        migrations.DeleteModel(
            name='maintain_history',
        ),
        migrations.DeleteModel(
            name='maintain_schedule',
        ),
        migrations.DeleteModel(
            name='staff',
        ),
    ]
