# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0012_auto_20151221_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time_remain',
            field=models.IntegerField(default=models.IntegerField(verbose_name='maintain type')),
        ),
    ]
