# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0013_auto_20151221_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time_remain',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_type',
            field=models.IntegerField(),
        ),
    ]
