# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0014_auto_20151222_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time_remain',
            field=models.IntegerField(default=100),
        ),
    ]
