# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0015_auto_20151222_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 1, 2, 9, 0, 42, 474611, tzinfo=utc)),
        ),
    ]
