# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0016_auto_20151223_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 23, 9, 3, 2, 286133, tzinfo=utc)),
        ),
    ]
