# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0017_auto_20151223_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 24, 9, 2, 44, 725419, tzinfo=utc)),
        ),
    ]
