# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0020_auto_20151226_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain_history',
            name='maintain_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 6, 50, 38, 63454, tzinfo=utc)),
        ),
    ]
