# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0022_auto_20151229_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain_history',
            name='approver',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_approve_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 7, 16, 31, 992020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_raise_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 7, 16, 32, 6669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 7, 16, 32, 7478, tzinfo=utc)),
        ),
    ]
