# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0023_auto_20151229_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain_history',
            name='comment',
            field=models.CharField(default='no comment', max_length=80),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_approve_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 7, 29, 6, 427998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_raise_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 7, 29, 6, 441446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 7, 29, 6, 442020, tzinfo=utc)),
        ),
    ]
