# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0024_auto_20151229_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain_history',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 8, 41, 39, 573519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_approve_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 8, 41, 39, 559939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_raise_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 8, 41, 39, 573475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 8, 41, 39, 574120, tzinfo=utc)),
        ),
    ]
