# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0028_auto_20160106_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_approve_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 18, 7, 9, 930391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_raise_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 18, 7, 9, 944895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 18, 7, 9, 944940, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 18, 7, 9, 945509, tzinfo=utc)),
        ),
    ]
