# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0030_auto_20160108_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='energy_today',
        ),
        migrations.AddField(
            model_name='counter_history',
            name='counter_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter_history',
            name='counter_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter_history',
            name='counter_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='counter_history',
            name='counter_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='counter_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='counter_size_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='counter_size_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='counter_size_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='counter_size_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='counter_history',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_approve_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 8, 21, 38, 910664, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_raise_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 8, 21, 38, 910741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_history',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 8, 21, 38, 910793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintain_schedule',
            name='maintain_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 8, 21, 38, 911543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='time_variable',
            name='last_update_maintain',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 1, 8, 21, 38, 891600, tzinfo=utc)),
        ),
    ]
